server:
  session-timeout: 1800
  #tomcat:
  #    max-threads: 1000
  #    min-spare-threads: 30
  port: 8080
  uri-encoding: utf-8
system:
  #注册用户默认密码
  defaultPwd: 123456
  #注册用户默认角色ID
  defaultRoleId: 100
  #注册用户默认组织机构ID
  defaultOrgId: 0
  #不需要数据权限过滤的角色key
  noDataFilterRole: DATA_NO_FILTER
  #用户每日收取短信上限
  smsTimes: 25
  #不同终端用户的超时时间（web用户3小时，app，微信，小程序时间自己定半年或永久）Long型，后面记得加l
  expireTime: "{web: 10800000l, app: 15768000000l}"
controller:
  #扫描controller中不需要鉴权的method
  scanPackage:
    classpath*:com/jeebase/*/*/controller/*.class
logging:
  path: /opt/server/logs
  config: classpath:config/logback-spring.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.116/huzhou?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: config,stat,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=false;
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
mybatis-plus:
  mapper-locations: classpath*:/com/jeebase/*/*/mapper/*Mapper.xml
  typeAliasesPackage: com.jeebase.*.*.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置
    logic-delete-value: 1
    logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
j2cache:
  config-location: classpath:config/j2cache.properties
  open-spring-cache: true
  j2CacheConfig:
    serialization: fastjson
  cache-clean-mode: active
  redis-client: jedis
qiniu:
  access-key:
  secret-key:
  zone: zone0
  bucket: mall
  base-url: http://img.jeebase.com/
aliyun:
  AccessKey-ID:
  Access-Key-Secret:
  sign-name:
  reg-code:
baidu:
  ai.clientId:
  ai.clientSecret:
restTemplate:
  #连接池的最大连接数默认为0
  maxTotalConnect: 0
  #单个主机的最大连接数
  maxConnectPerRoute: 200
  #连接超时默认2s
  connectTimeout: 2000
  #读取超时默认30s
  readTimeout: 30000

opcServer:
  host: 192.168.0.101
  user: OPCuser
  password: Dyrj888
  domain:
  clsid : 7BC0CC8E-482C-47CA-ABDC--0FE7F9C6E729
